### PR TITLE
ES6 Refactor

### PR DESCRIPTION
**Pull request by mlenser**
Ok so this is the ES6 refactor. There is very little code change (mostly just moving things around) so this should have no impact on how it works, but I haven't tested it at all. I've run out of time, but can test it more on Wednesday (I play on Tuesdays).

I think there is a lot of optimization to be done and will continue on that then.

Make sure you have `yarn` installed globally by running `npm install -g yarn` and then you can run `yarn` in the terminal to install everything properly.

### CODE REVIEW

**Comment by arthur-bauer** [comment]
Uff... Thanks, that's awesome, @mlenser! 
I need a bit to dig through it so I understand what you did, though.

**Comment by mlenser** [comment]
Short summary:

- `node_modules` shouldn't be stored on git, so I removed those. That's 99% of the files changed. Developers can run `yarn` to install it all (same thing for repos that use npm)
- Indentation. Most lines changed are indentation
- Use `Yarn` instead of `Npm`. Yarn is quite similar, just more effecient and slightly different syntax for adding dependencies. I can give you a run down if you're confused on any of that.
- Use EcmaScript 6 (aka ES6, aka ES 2015), converting to ES5 when built
  - Use fat arrow functions
  - Replace string concatenation (`x + 'hello' + y`) with string literals. `${x}hello${y}`
- Add some standard git files like `.babelrc`, `.gitignore`

You can also look at each commit if it's easier. I did it somewhat sequentially. (https://github.com/arthur-bauer/roll20-cashmaster/pull/16/commits)

The code itself should be largely unchanged. I have some ideas to improve that, but that's for Wednesday.

**Comment by arthur-bauer** [comment]
- Ok, I see the reason behind the `node-modules`. Wasn't sure if it makes sense to keep them in the repo or not, so I thought "better safe than sorry".
- Need to read about `Yarn` a bit... 
- Fine with the indentations. I really suck at using proper indentations.
-  Part about `ES6` is clear.
- `Babel` compiles the ES6 code to "old" code during the build, I assume?

**Comment by mlenser** [comment]
Babel compiles to EcmaScript 5 (ES5), which is what browsers used for quite a long time. Most browsers and environments support ES6 or even ES2016+ (aka ES7 and ES8), but Roll20 used to use an old version of node so I've always converted to ES5 to ensure it works. ES6 might work since Riley updated the version of node about 6-8 months ago. I can ask Aaron about that.

https://blog.risingstack.com/yarn-vs-npm-node-js-package-managers/ discusses yarn vs npm. I've worked on a few professional projects in the last 2 years and all are on Yarn. Though from what I read NPM 4 made a big comback in that regard and the differences are smaller now. Both are popular in the JS community.
https://medium.com/netscape/npm-5-yarn-killer-ba69737b24d0 shows a speed comparison of npm5 vs yarn. Yarn is still ahead.

**Comment by arthur-bauer** [comment]
Ok. Get the yarn part now as well. So instead of adding the 20MB node-modules, I just add the `yarn.lock` to the repo and anyone else just runs yarn to get all the packages. Neat.

**Comment by mlenser** [comment]
Npm would be the same, but use `npm install` instead of `yarn` to get all the dependencies.

**Pull request merged**
